import {
    Button,
    Spinner,
    VerticalBox,
    GridBox,
    HorizontalBox,
    ComboBox,
    Palette,
    LineEdit,
    StyleMetrics,
    CheckBox,
    GroupBox,
    Slider,
    SpinBox,
} from "std-widgets.slint";

import { FilePickerInput } from "./inputs.slint";
import { LabelBox } from "inputs.slint";

struct CompressionSettings {
    enabled: bool,
    level: int,
}

export component AppWindow inherits Window {
    in property <bool> file-dialog-opened;
    in property <bool> loading;
    in property <bool> image-loaded;
    in property <bool> processing-image;
    in property <[string]> viewer-mode-model;
    in property <[string]> texture-type-model;
    in property <[string]> resize-method-model;
    in property <[string]> resize-filter-model;
    in property <string> output-folder-path;
    in property <string> input-path;
    in property <int> max-index: 999;
    in property <image> viewer-image;

    in-out property <CompressionSettings> compression-settings: { enabled: true, level: 6 };
    in-out property <string> viewer-mode;
    in-out property <string> texture-type;
    in-out property <string> resize-method;
    in-out property <string> resize-filter;
    in-out property <int> item-index;

    callback pick_file_input();
    callback pick_file_output();
    callback pick_folder_output();
    callback export_button_clicked();
    callback update_preview();

    title: "Tomo Paint Converter";
    min-width: 800px;
    min-height: 600px;
    HorizontalLayout {
        visible: image-loaded;
        VerticalLayout {
            horizontal-stretch: 1;
            Rectangle {
                background: Palette.alternate-background;
                HorizontalBox {
                    alignment: end;

                    HorizontalLayout {
                        spacing: 0.5rem;
                        Text {
                            text: "Viewer Mode";
                            vertical-alignment: center;
                        }

                        ComboBox {
                            model: viewer-mode-model;
                            current-value <=> viewer-mode;
                        }
                    }
                }
            }

            Rectangle {
                vertical-stretch: 1;

                Rectangle {
                    background: black;
                    opacity: 0.5;
                    visible: processing-image;
                    VerticalBox {
                        alignment: center;
                        Spinner {
                            indeterminate: true;
                            preferred-width: 3rem;
                            horizontal-stretch: 0;
                        }

                        Text {
                            text: "Processing Image...";
                            vertical-alignment: center;
                            horizontal-alignment: center;
                        }
                    }
                }

                GridLayout {
                    Row {
                        Image {
                            vertical-stretch: 1;
                            source: viewer-image;
                        }
                    }

                    Row {
                        HorizontalLayout {
                            alignment: start;
                            padding: 0.5rem;
                            spacing: 0.5rem;
                            Text {
                                text: viewer-image.width + "x" + viewer-image.height;
                                vertical-alignment: center;
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            background: Palette.alternate-background;
            preferred-width: 300px;
            VerticalBox {
                horizontal-stretch: 0;
                alignment: space-between;
                VerticalBox {
                    alignment: start;
                    LabelBox {
                        label: "Input";
                        FilePickerInput {
                            path: input-path;
                            enabled: !loading;
                            pick-requested => {
                                pick_file_input();
                            }
                        }
                    }

                    LabelBox {
                        label: "Texture Type";
                        ComboBox {
                            model: texture-type-model;
                            current-value <=> texture-type;
                            selected() => update_preview();
                        }
                    }

                    LabelBox {
                        label: "Item Index";
                        SpinBox {
                            minimum: 0;
                            maximum: max-index;
                            value <=> item-index;
                        }
                    }

                    LabelBox {
                        label: "Resize Method";
                        ComboBox {
                            model: resize-method-model;
                            current-value <=> resize-method;
                            selected() => update_preview();
                        }
                    }

                    LabelBox {
                        label: "Resize Filter";
                        ComboBox {
                            model: resize-filter-model;
                            current-value <=> resize-filter;
                            selected() => update_preview();
                        }
                    }

                    LabelBox {
                        label: "Compression";
                        VerticalLayout {
                            CheckBox {
                                text: "Enabled";
                                checked <=> compression-settings.enabled;
                            }
                        }
                    }

                    LabelBox {
                        label: "Compression Level";
                        HorizontalLayout {
                            Slider {
                                horizontal-stretch: 1;
                                minimum: 0;
                                maximum: 20;
                                enabled: compression-settings.enabled;
                                value: compression-settings.level;
                                changed => {
                                    compression-settings.level = self.value;
                                }
                            }

                            Text {
                                width: 2rem;
                                opacity: compression-settings.enabled ? 1 : 0.5;
                                horizontal-stretch: 0;
                                text: compression-settings.level;
                                horizontal-alignment: center;
                                vertical-alignment: center;
                            }
                        }
                    }

                    LabelBox {
                        label: "Output Directory";
                        FilePickerInput {
                            path: output-folder-path;
                            enabled: !loading;
                            pick-requested => {
                                pick_folder_output();
                            }
                        }
                    }
                }

                Button {
                    text: "Export";
                    primary: !loading && !file-dialog-opened;
                    enabled: !loading;
                    clicked => {
                        export_button_clicked();
                    };
                }
            }
        }
    }

    VerticalBox {
        y: image-loaded ? root.height : 0;
        opacity: image-loaded ? 0 : 1;
        alignment: center;
        spacing: 0.5rem;

        animate y {
            duration: 0.5s;
            easing: ease-in-out;
        }
        animate opacity {
            duration: 0.25s;
            easing: ease-in-out;
        }

        Text {
            text: "Tomo Paint Converter";
            font-weight: 900;
            font-size: 1.5rem;
            horizontal-alignment: center;
        }

        VerticalBox {
            alignment: center;
            spacing: 0.5rem;

            Text {
                text: "Import image or texture to convert";
                horizontal-alignment: center;
            }

            Button {
                enabled: !loading && !image-loaded;
                colorize-icon: true;
                icon: @image-url("images/folder.svg");
                icon-size: 1.25rem;
                text: "Choose File";
                primary: true;
                clicked => {
                    self.enabled = false;
                    pick_file_input();
                };
            }
        }
    }

    Rectangle {
        opacity: 0.5;
        background: black;
        visible: loading;

        VerticalBox {
            alignment: center;
            loading-spinner := Spinner {
                preferred-width: 3rem;
                horizontal-stretch: 0;
            }

            loading-text := Text {
                text: "Loading...";
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }
}
