import {
    Button,
    Spinner,
    VerticalBox,
    GridBox,
    HorizontalBox,
    ComboBox,
    Palette,
    LineEdit,
    StyleMetrics,
    CheckBox,
    GroupBox,
    Slider,
    SpinBox,
} from "std-widgets.slint";

import { FilePickerInput } from "./inputs.slint";
import { LabelBox } from "inputs.slint";
import { ImageViewer } from "image-viewer.slint";

struct CompressionSettings {
    enabled: bool,
    level: int,
}

export component AppWindow inherits Window {
    in property <bool> file-dialog-opened;
    in property <bool> loading;
    in property <bool> image-loaded;
    in property <bool> processing-image;
    in property <bool> saving;
    in property <[string]> viewer-mode-model;
    in property <[string]> texture-type-model;
    in property <[string]> resize-method-model;
    in property <[string]> resize-filter-model;
    in property <string> output-folder-path;
    in property <string> input-path;
    in property <int> max-index: 999;
    in property <image> viewer-image;

    in-out property <CompressionSettings> compression-settings: { enabled: true, level: 6 };
    in-out property <string> viewer-mode;
    in-out property <string> texture-type;
    in-out property <string> resize-method;
    in-out property <string> resize-filter;
    in-out property <int> item-index;

    callback pick_file_input();
    callback export_button_clicked();
    callback update_preview();

    title: "Tomo Paint Converter";
    min-width: 800px;
    min-height: 600px;
    HorizontalLayout {
        visible: image-loaded;
        VerticalLayout {
            horizontal-stretch: 1;
            Rectangle {
                background: Palette.alternate-background;
                HorizontalBox {
                    alignment: end;

                    HorizontalLayout {
                        spacing: 0.5rem;
                        Text {
                            text: "Preview Mode";
                            vertical-alignment: center;
                        }

                        ComboBox {
                            enabled: !processing-image && !loading && !saving && !file-dialog-opened;
                            model: viewer-mode-model;
                            current-value <=> viewer-mode;
                            selected() => {
                                update_preview();
                            }
                        }
                    }
                }
            }

            Rectangle {
                vertical-stretch: 1;

                VerticalLayout {
                    property <float> zoom: 1.0;
                    property <bool> manual-zoom: false;
                    property <float> min-zoom: 0.01;
                    property <float> max-zoom: 8.0;

                    Timer {
                        interval: 10ms;
                        running: true;
                        triggered => {
                            if (manual-zoom || zoom == viewer.zoom) {
                                return;
                            }
                            zoom = viewer.zoom;
                        }
                    }

                    HorizontalLayout {
                        alignment: space-between;
                        padding: 0.5rem;
                        spacing: 0.5rem;
                        HorizontalLayout {
                            Text {
                                text: "Zoom";
                                vertical-alignment: center;
                                forward-focus: slider;
                            }

                            slider := Slider {
                                width: 15rem;
                                minimum: min-zoom;
                                maximum: max-zoom;
                                value: zoom;
                                changed(value) => {
                                    if (viewer.zoom != value) {
                                        viewer.set-zoom(value);
                                    }
                                }
                            }

                            Text {
                                text: zoom * 100 + "%";
                                vertical-alignment: center;
                            }
                        }

                        Button {
                            text: "Fit to View";
                            primary: viewer.fit-to-view;
                            clicked => {
                                if (!viewer.fit-to-view) {
                                    viewer.fit-view();
                                }
                            }
                        }
                    }

                    viewer := ImageViewer {
                        source: viewer-image;
                    }

                    HorizontalLayout {
                        alignment: start;
                        padding: 0.5rem;
                        spacing: 0.5rem;
                        Text {
                            text: viewer-image.width + "x" + viewer-image.height;
                            vertical-alignment: center;
                        }
                    }
                }

                Rectangle {
                    background: rgba(0, 0, 0, 0.5);
                    visible: processing-image;
                    VerticalBox {
                        alignment: center;
                        spacing: 2rem;
                        Image {
                            preferred-height: 12rem;
                            source: @image-url("images/loading/cat.png");
                            transform-rotation: sin(360deg * animation-tick() / 10s) * 10deg;
                            transform-scale-x: abs(sin(360deg * animation-tick() / 3300ms) * 0.25) + 1;
                            transform-scale-y: abs(sin(360deg * animation-tick() / 3301ms) * 0.25) + 1;
                        }

                        Text {
                            text: "Processing image...";
                            vertical-alignment: center;
                            horizontal-alignment: center;
                        }
                    }
                }
            }
        }

        Rectangle {
            background: Palette.alternate-background;
            preferred-width: 300px;
            VerticalBox {
                horizontal-stretch: 0;
                alignment: space-between;
                VerticalBox {
                    alignment: start;
                    LabelBox {
                        label: "Input";
                        FilePickerInput {
                            path: input-path;
                            enabled: !loading && !processing-image && !saving && !file-dialog-opened;
                            pick-requested => {
                                pick_file_input();
                            }
                        }
                    }

                    LabelBox {
                        label: "Texture Type";
                        ComboBox {
                            enabled: !loading && !processing-image && !saving && !file-dialog-opened;
                            model: texture-type-model;
                            current-value <=> texture-type;
                            selected() => update_preview();
                        }
                    }

                    LabelBox {
                        label: "Item Index";
                        SpinBox {
                            enabled: !loading && !processing-image && !saving && !file-dialog-opened;
                            minimum: 0;
                            maximum: max-index;
                            value <=> item-index;
                        }
                    }

                    LabelBox {
                        label: "Resize Method";
                        ComboBox {
                            enabled: !loading && !processing-image && !saving && !file-dialog-opened;
                            model: resize-method-model;
                            current-value <=> resize-method;
                            selected() => update_preview();
                        }
                    }

                    LabelBox {
                        label: "Resize Filter";
                        ComboBox {
                            enabled: !loading && !processing-image && !saving && !file-dialog-opened;
                            model: resize-filter-model;
                            current-value <=> resize-filter;
                            selected() => update_preview();
                        }
                    }

                    LabelBox {
                        label: "Compression";
                        VerticalLayout {
                            CheckBox {
                                text: "Enabled";
                                enabled: !saving;
                                checked <=> compression-settings.enabled;
                            }
                        }
                    }

                    LabelBox {
                        label: "Compression Level";
                        HorizontalLayout {
                            Slider {
                                horizontal-stretch: 1;
                                minimum: 0;
                                maximum: 20;
                                enabled: compression-settings.enabled && !saving;
                                value: compression-settings.level;
                                changed => {
                                    compression-settings.level = self.value;
                                }
                            }

                            Text {
                                width: 2rem;
                                opacity: compression-settings.enabled ? 1 : 0.5;
                                horizontal-stretch: 0;
                                text: compression-settings.level;
                                horizontal-alignment: center;
                                vertical-alignment: center;
                            }
                        }
                    }
                }

                Button {
                    text: saving ? "Exporting..." : "Export";
                    opacity: saving ? abs(sin(360deg * animation-tick() / 3300ms) * 0.25) + 1 : 1;
                    primary: !loading && !file-dialog-opened && !processing-image;
                    enabled: !loading && !file-dialog-opened && !processing-image;
                    clicked => {
                        export_button_clicked();
                    };
                }
            }
        }
    }

    VerticalBox {
        y: image-loaded ? root.height : 0;
        opacity: image-loaded ? 0 : 1;
        alignment: center;
        spacing: 0.5rem;

        animate y {
            duration: 0.5s;
            easing: ease-in-out;
        }
        animate opacity {
            duration: 0.25s;
            easing: ease-in-out;
        }

        Text {
            text: "Tomo Paint Converter";
            font-weight: 900;
            font-size: 1.5rem;
            horizontal-alignment: center;
        }

        Text {
            text: "Import image or texture to convert";
            horizontal-alignment: center;
        }

        Rectangle {
            Button {
                preferred-width: 250px;
                enabled: !loading && !image-loaded;
                colorize-icon: true;
                icon: @image-url("images/folder.svg");
                icon-size: 1.25rem;
                text: "Choose File";
                primary: true;
                clicked => {
                    self.enabled = false;
                    pick_file_input();
                };
            }
        }
    }

    Rectangle {
        background: rgba(0, 0, 0, 0.5);
        visible: loading;

        VerticalBox {
            alignment: center;
            Image {
                source: @image-url("images/loading/snek.png");
                preferred-height: 8rem;
                transform-rotation: sin(360deg * animation-tick() / 10s) * 10deg;
                transform-scale-x: abs(sin(360deg * animation-tick() / 3300ms) * 0.25) + 1;
                transform-scale-y: abs(sin(360deg * animation-tick() / 3301ms) * 0.25) + 1;
            }

            loading-text := Text {
                text: "Importing file...";
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }
}
