import { Palette } from "std-widgets.slint";
export component PopupMessage {

    in property <duration> timeout: 2.5s;

    public function show() {
        root.opacity = 1;
    }

    public function hide() {
        root.opacity = 0;
    }

    opacity: 0;

    animate opacity {
        duration: 0.5s;
        easing: ease-in-out;
    }

    TouchArea {
        enabled: parent.opacity == 1;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.up) {
                root.opacity = 0;
                return EventResult.accept;
            }
            return EventResult.reject;
        }
    }

    Timer {
        interval: timeout;
        running: root.opacity > 0;
        triggered() => {
            root.opacity = 0;
        }
    }

    VerticalLayout {
        alignment: center;

        HorizontalLayout {
            alignment: center;

            Rectangle {
                background: Palette.alternate-background.with-alpha(0.9);
                drop-shadow-blur: 1rem;
                drop-shadow-color: rgba(0, 0, 0, 0.5);
                border-radius: 0.5rem;
                horizontal-stretch: 0;
                preferred-width: 300px;

                @children
            }
        }
    }
}
